### PR TITLE
Use doit to simplify management of project

### PR DESCRIPTION
**Pull request by ceball**
This PR demos "doit" as a way of reducing the complexity of performing various tasks (installation, running tests, etc). 

I can easily imagine someone having no opinion about this, or wondering why we need another tool. I think for any one project, you don't need anything, but when you end up with lots of projects it all becomes a bit of nightmare. This is my attempt at improving things. Yes, it would be better if python had standard commands to run tests, install various dependencies, build docs, etc, but it doesn't (as far as I know). Tox is a project trying to achieve something like that, but we can't currently use it with conda (although it seems good for param).

I would love not to have this, so if you can think of a better way, please say. At least doit is just running existing commands, and doesn't become a dependency - i.e. using it is completely optional.

Some good and bad points that I can think of (please edit/comment):

Good:

* adds windows testing
* Platform-specific bash can be eliminated by using python (which allows windows to run the same commands without having to write cmd/powershell) 
* travis file has shrunk (and appveyor file has same commands - just config is unavoidably different)
* same commands can be run locally as on CI systems
* Fewer and shorter commands are required by users/developers.
* Common tasks can be defined once and shared between projects (currently via "ioamdoit", but that's just for testing)
* Tasks can have dependencies and depend on other tasks, allowing groups of tasks to be run easily.
* doit has the concept of targets, up to date checks, etc, so works for partial re-running (e.g. if a project has lots of expensive-to-run notebooks or similar).

Bad:

* Some tasks are similar to/no better than their underlying command. E.g. `doit lint` currently runs `'flake8 --ignore E,W parambokeh` but that could be reduced to just `flake8` by adding some flake8 config to setup.cfg.
* Some commands don't work well as doit tasks. E.g. you can't `source activate` from doit.
* Another thing
* Is dodo.py declarative/config enough? E.g. consider anaconda-project.
* Why not tox? conda is incompatible with tox. (tox also doesn't have dependencies/targets, but we could probably get away without those.)

Notes:

* Tasks could be split up/organized in better ways if we decided to go ahead - just demonstrating the potential.
* This dodo.py file doesn't demonstrate various additional make-like features of dodo (e.g. targets, up to date checks, etc).
* To explain a complication in the travis file related to installing miniconda...On travis, basic python 2.7 is available (even on 'generic' images). Therefore, it's convenient to download and install miniconda using python/doit, because that avoids platform-specific shell commands. However, travis python is 2.7, and the latest doit only supports python 3, so first an old version of doit is installed and used to install miniconda, then current doit is installed into miniconda. It's a shame travis doesn't include miniconda (unless I missed it; appveyor does include miniconda).

### CODE REVIEW

**Comment by ceball** [comment]
Note: appveyor completed and is green, but github was down.

**Review by jbednar — COMMENTED** [review]
Looks good to me!

**Review by philippjfr — APPROVED** [review]
Looks fine to me as well. I think I'd prefer tox if it eventually supports conda, but I don't think that should block anything.

**Comment by ceball** [comment]
Yes, it should be easy to switch away from doit in the future, as long as tasks are generally kept to calling existing (external), simple commands.

For a straightforward python software project (e.g. param), tox is great.

Doit becomes handy when your project starts needing additional things, e.g. to download datasets before performing some tasks. Some of this aspect probably overlaps a bit with something like anaconda project.

Doit also becomes handy for less standardized tasks around managing a software project, where there aren't (yet) standard commands, or it's all a bit messy.

**Pull request merged**
