### PR TITLE
Use nbsmoke to 'run' and 'lint' test notebooks

### PR DESCRIPTION
**Pull request by ceball**
"nbsane" is a pytest plugin that can run notebooks (optionally saving to html) and lint them, e.g.

screen shot 2017-10-23 at 11 53 00 am

screen shot 2017-10-23 at 11 53 28 am

Storing html can be done with e.g. `pytest --nbsane-run --store-html=/path/to/store/in doc/`.

It uses nbconvert, so is simpler than nbval (which has different goals).

It's good because:
* it reduces duplication across projects (instead of copying in test_notebooks script)
* it's fully cross platform (test_notebooks used sed for lint checking)
* it fits into a standard, well-known testing tool

It's bad because:
* it's different from nbval (nbval has different goals, but there are some similarities; may be possible to merge in the future)
* it's new and will no doubt have problems (needs to be tested in real world)
* it had to be written

### CODE REVIEW

**Comment by ceball** [comment]
"nbsane" is a pytest plugin that can run notebooks (optionally saving to html) and lint them:

screen shot 2017-10-23 at 11 53 00 am

screen shot 2017-10-23 at 11 53 28 am

It uses nbconvert, so is simpler than nbval (which has different goals).

**Comment by jbednar** [comment]
Sounds good, but I think `nbsane` may be promising too much!  I assume `nbsanitycheck` is what you mean but decided it was too long, and `nblint` is already taken, so how about `nbsmoke` (for smoke testing)?

**Comment by ceball** [comment]
Right :) nbsmoke is more suggestive of the dangers to which you're still subjecting yourself; couldn't quite think that one up myself. I can rename when I move from my github account to elsewhere (to ContinuumIO, or maybe ioam?).

Basically it's two classes:

```
class RunNb(pytest.Item):
    def runtest(self):
        with io.open(self.name,encoding='utf8') as nb:
            nbconvert.ExecutePreprocessor(...).preprocess(nbformat.read(nb, as_version=4),{})

class LintNb(pytest.Item):
    def runtest(self):
        with io.open(self.name,encoding='utf8') as nb:
            py, resources = nbconvert.PythonExporter().from_notebook_node(nbformat.read(nb, as_version=4))
            if flakes.check(py,self.name) != 0:
                raise AssertionError
```

But there's a lot of auto-generated pytest boilerplate. And I wrote some tests. It doesn't quite test itself using itself, but at least it uses pytest ;)

**Comment by jbednar** [comment]
Sounds good.

**Comment by jbednar** [comment]
Should this be merged now, or wait until the project is moved and renamed?

**Comment by ceball** [comment]
Planning to move and rename first.

**Comment by ceball** [comment]
I think we can ignore the test failure above on travis

```
[...]
$ conda install -c conda-forge "holoviews>=1.8.4"
conda install -c conda-forge "holoviews>=1.8.4" 
Fetching package metadata ......
CondaHTTPError: HTTP 504 GATEWAY TIME-OUT for url <https://repo.continuum.io/pkgs/main/noarch/repodata.json.bz2>
```

**Comment by ceball** [comment]
I switched the reviewer because maybe I finally found a time when Philipp isn't working ;)

**Comment by jbednar** [comment]
He *is* working, he's just (a) on a train, and (b) releasing GeoViews.

**Review by jbednar — APPROVED** [review]
How could anyone object to a PR that adds 3 lines while removing 92?

**Pull request merged**
