### PR TITLE
Add height kwarg to Widgets

### PR DESCRIPTION
**Pull request by ahuang11**

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks good, happy to merge if it works for you as expected.

**Comment by jbednar** [comment]
I can't quite tell how this is meant to work. What happens when there are small numbers of widgets?  Does the box now have empty space?  Seems like this would have been something to define as None by default and only apply if someone explicitly sets it?  I may be confused, though.

**Comment by philippjfr** [comment]
> Seems like this would have been something to define as None by default and only apply if someone explicitly sets it?

I think you're right about that, or alternatively it should switch between width and height depending on whether it's a row or column layout. @ahuang11 What's the behavior with this PR like?

**Comment by ahuang11** [comment]
I just tested it; it actually doesn't seem to be doing anything; I was hoping it would create more spacing between the widgets. Also tested in server mode; no difference.

image

image

**Comment by jbednar** [comment]
Should we go ahead and close this?

**Pull request closed without merging**
